### PR TITLE
Update styletts_to_ebook.py

### PR DESCRIPTION
**Pull request by partrita**
To fix `temp_ebook` directory error.

```shell
❯ python styletts_to_ebook.py ../input/
[nltk_data] Downloading package punkt to /home/fkt/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Created directory: ./Working_files/Book
The file ./Working_files/temp.epub does not exist.
Traceback (most recent call last):
  File "/usr/bin/ebook-convert", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 379, in main
    parser, plumber = create_option_parser(args, log)
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 332, in create_option_parser
    plumber = Plumber(input, output, log, reporter)
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 723, in __init__
    raise ValueError('Input file must have an extension')
ValueError: Input file must have an extension
An error occurred while converting the eBook: Command '['ebook-convert', '../input/', './Working_files/temp.epub']' returned non-zero exit status 1.
[nltk_data] Downloading package punkt to /home/fkt/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "/media/fkt/82c1c9f8-5b60-449e-b3b1-2710aabe45ee/TTS2ebook/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 332, in <module>
    create_chapter_labeled_book(ebook_file_path)
  File "/media/fkt/82c1c9f8-5b60-449e-b3b1-2710aabe45ee/TTS2ebook/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 237, in create_chapter_labeled_book
    process_chapter_files(folder_path, output_csv)
  File "/media/fkt/82c1c9f8-5b60-449e-b3b1-2710aabe45ee/TTS2ebook/ebook2audiobookSTYLETTS2/styletts_to_ebook.py", line 213, in process_chapter_files
    chapter_files = sorted(os.listdir(folder_path), key=lambda x: int(x.split('_')[1].split('.')[0]))
                           ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Working_files/temp_ebook'
```

### CODE REVIEW

**Comment by DrewThomasson** [comment]
Interesting... my ensure_directory function didn't end up doing its job in this case?

**Comment by partrita** [comment]
> Interesting... my ensure_directory function didn't end up doing its job in this case?

In my case? yes. I am not sure why though.

**Comment by DrewThomasson** [comment]
Welp, as long as it fixed your issue I don't see any reason not to push it

Thx!

**Review by DrewThomasson — COMMENTED** [review]
Fix

**Comment by DrewThomasson** [comment]
I'll do a full test tomorrow on windows wsl, Ubuntu, Mac, and apple silicone with this updated code

**Pull request merged**
